### ISSUE TITLE
Compatible with themes

### ISSUE THREAD

**Issue by rodica-andronache** [kungtiger/central-color-palette#2]
Hi,
Great plugin! I was wondering what we could do, to make the plugin support two of our themes https://wordpress.org/themes/neve/ and https://wordpress.org/themes/hestia/.

Thanks

**Comment by rodica-andronache** [comment]
Hi @kungtiger, 
If you could help me with that info, I would be thankful :)

**Comment by kungtiger** [comment]
Hi Rodica,
apologies for the late reply. I'm not very active on github.

Both your themes do support my plugin out of the box. It's one of those cases where my plugin automatically supports a theme but it's not clear from the palette editor. There was a similar issue with Astra Theme and I've solved it by adding a note next to the option that integrates the central palette with the Theme Customizer. That's what I can do.

Now, about Hestia: it looks like it (mostly) works out of the box. Inside the Customizer so far I've discovered three colour picker of which one does not show the central palette. I'll dig into that and maybe I'll get him to work.

**Comment by rodica-andronache** [comment]
Hi @kungtiger,

Thank you for the answer, I really appreciate it :) 
If there is something I can do from my side, just let me know. The plugin is really interesting, and we would love it to support our themes too.

**Comment by kungtiger** [comment]
Thanks for the feedback.

If think if you were to add a filter to `hestia/inc/customizer/general/class-hestia-color-controls.php` on line 27 I would be able to add my central palette to your customizer control. Something like
`'palette'  => apply_filters('hestia_accent_color_palette', false),` would do just fine.

Also I've committed the latest version 1.13.1 of my plugin so in case you are sourcing my plugin from github we're looking at the same thing.

**Comment by rodica-andronache** [comment]
Hi @kungtiger,
So sorry for the late reply. We will add the filter in the next release, at which we are currently working. I will let you know when that happens.

Thank you

**Comment by rodica-andronache** [comment]
Hi @kungtiger,

Thank you for your patience. We've added the filter in Hestia. Let me know if there's something else I can do.

Thank you

**Comment by kungtiger** [comment]
Great! Have a look at the latest version here on github and let me know if it works for you.

**Comment by rodica-andronache** [comment]
Hi @kungtiger,
It works great, both in Neve and Hestia. Thanks so much. Looking forward to the update.

**Comment by kungtiger** [comment]
version 1.13.3 is out.
