### ISSUE TITLE
Compatibility Issue with last version of Elementor & Elementor Pro

### ISSUE THREAD

**Issue by black-eye** [kungtiger/central-color-palette#3]
Please, checkout this issue here: https://github.com/pojome/elementor/issues/6771
I found out that it's is caused by your plugin.

When your plugin is active, Editor with limited access to Elementor cannot exit editing the page due missing Exit to Dashboard button.

You'll need to have EPro version activated.

**Comment by kungtiger** [comment]
Thanks for letting me know. Version 1.13.2 will remove this issue.

**Comment by black-eye** [comment]
Excelent! Confirming, the button is back again. Thanks for a quick fix.
